report build status

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -38,12 +38,26 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
 
+  report-build-status:
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ always() }}
+    steps:
+      - name: Report build status
+        run: |
+          if [ "${{ needs.build.result }}" = "success" ]; then
+            echo "Build OK"
+          else
+            echo "Build failed"
+            exit 1
+          fi
+
   deploy:
+    runs-on: ubuntu-latest
+    needs: [build, report-build-status]
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
-    runs-on: ubuntu-latest
-    needs: build
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
